import type { Metadata } from "next";
import { Geist, Geist_Mono, Outfit, Young_Serif, Inter,Manrope } from "next/font/google";
import "./globals.css";

const manrope= Manrope({subsets:["latin"],variable:"--font-manrope"}) 
const inter = Inter({variable:"--font-inter",subsets:["latin"]});
const youngSerif = Young_Serif({ variable: "--font-young-serif", subsets: ["latin"], weight: ["400"] });
const outfit = Outfit({ variable: "--font-outfit",subsets["latin"] });
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Front end Mentor practices",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${outfit.variable} ${youngSerif.variable} ${inter.variable} ${manrope.variable}  antialiased`}>
        <main>{children}</main>
        <footer className="attribution">
          Challenge by{" "}
          <a href="https://www.frontendmentor.io?ref=challenge" target="_blank">
            Frontend Mentor
          </a>
          . Coded by <a href="#">Your Name Here</a>.
        </footer>
      </body>
    </html>
  );
}
